### ISSUE TITLE
Features not in order

### ISSUE THREAD

**Issue by AuRobinson** [qwertzuiopy/Libellus#1]
## Issue

Level features listed in lexicographical order rather than numerical order for the following,
- Class
- Subclass

## Current build

```
username@hostname:~$ flatpak list --columns=name,application,version | grep "Libellus"

Michael Hammer	de.hummdudel.Libellus	1.0.3
```

## Supporting images

![image](https://github.com/qwertzuiopy/Libellus/assets/95049035/1af246c1-f2a6-4b61-8510-890269f86893)

![image](https://github.com/qwertzuiopy/Libellus/assets/95049035/57c5d789-676d-4d5c-b795-0786becfc79b)

**Comment by qwertzuiopy** [comment]
oops

**Comment by qwertzuiopy** [comment]
Fixed by https://github.com/qwertzuiopy/Libellus/commit/a820422f794d6bc3d126b132956f81595ceda837
