### ISSUE TITLE
Latest update breaks a lot

### ISSUE THREAD

**Issue by Henry-Hiles** [qwertzuiopy/Libellus#10]
Sometimes the app doesnt even open (says sources is undefined), and if it does open, touch events don't work so I can't open anything.

**Comment by Henry-Hiles** [comment]
Oh huh. `rm -rf ~/.var/app/de.hummdudel.Libellus` fixes it. Should this be done automatically as a migration step?

**Comment by qwertzuiopy** [comment]
well, oops. Should be fixed in https://github.com/qwertzuiopy/Libellus/commit/0d2af3a6f7096f162dcb4d3c1cee0c09c5d5dddc, thank you!
The app now checks whether the save file has the correct fields rather than just assuming it has.
