### ISSUE TITLE
The page for 'Monk' isn't adaptive  

### ISSUE THREAD

**Issue by MadameMalady** [qwertzuiopy/Libellus#2]
The page or Monk isn't adaptive, here's the way it looks for the other pages ( Druid ), and how it looks for the Monk:
![Screenshot from 2024-06-29 01-42-01](https://github.com/qwertzuiopy/Libellus/assets/41642242/5fe668af-b51f-438a-8bed-a9c7e0b9a6c6)
![Screenshot from 2024-06-29 01-42-13](https://github.com/qwertzuiopy/Libellus/assets/41642242/864f36f1-a286-46a0-a7c0-199f9d2ded95)

**Comment by qwertzuiopy** [comment]
Fixed by https://github.com/qwertzuiopy/Libellus/commit/54bc89e3f6704bb7435acdcb8e4e3c7c5c4f0dcf, thank you!
