### ISSUE TITLE
Spell slots per level seem to be out of order

### ISSUE THREAD

**Issue by nydragon** [qwertzuiopy/Libellus#5]
The spell slot distribution displayed inside libellus is correct for lvl 1. but from 
lvl 2-11 it corresponds to the stats at 10-19.
12 corresponds to lvl. 2
lvl 13 us lvl 20
13-20 maps to 3-9

Have checked cleric & wizard

**Comment by qwertzuiopy** [comment]
I think this should be fixed alongside https://github.com/qwertzuiopy/Libellus/issues/1 in commit https://github.com/qwertzuiopy/Libellus/commit/a820422f794d6bc3d126b132956f81595ceda837, can you check that this is still happening in version 1.0.4?

**Comment by nydragon** [comment]
Can confirm, thank you!
