### ISSUE TITLE
Low contrast for dark brand color

### ISSUE THREAD

**Issue by bragefuglseth** [qwertzuiopy/Libellus#6]
Hi! Libelius is featured on Flathub this week, and I noticed that its dark brand color is so dark that there’s barely any contrast between it and the website background. In fact, I’m pretty sure it matches exactly. Maybe it should be changed so this is not the case? The other featured apps give a good indication of how good the contrast should be.

![IMG_7755](https://github.com/user-attachments/assets/5d2c7dc2-33f5-4bc3-a176-5b5489dd9738)

**Comment by qwertzuiopy** [comment]
Fixed in https://github.com/qwertzuiopy/Libellus/commit/957b052013d36db56778d7964cc2c6a364a63565, thank you!
