### ISSUE TITLE
[object Object] spell slots for sorcerer

### ISSUE THREAD

**Issue by Henry-Hiles** [qwertzuiopy/Libellus#8]
If you look at Sorcerer's stats at any level other than 1 (level 2 for example), you'll see a lot of values that just say [object Object]. Also, a lot of titles are in lowercase. Thanks for this amazing app, I hope this can get fixed!

**Comment by qwertzuiopy** [comment]
Fixed by https://github.com/qwertzuiopy/Libellus/commit/d82b172b2c5660b2b9fe3699e8f638f2fccadb70, thank you so much for reporting this!
